# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 宅首围
email: 66903041@qq.com
description: > # 做一条有逼格的程序狗
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
zhihu_username: liu-kun-66-25
github_username:  tough1985
weibo_username:  zhaishouwei
copyright_name: 宅首围
header-img: assets/img/home-bg3.jpg

# Build settings
markdown: kramdown
# theme: minima

# Jekyll
#sass文件路径和打包方式
sass:
  sass_dir:   _sass
  style:      compressed